### ISSUE TITLE
Improve import paths and use `fancyscript-yaml` package

### ISSUE THREAD

**Issue by LonelyDeathVGX** [FancyStudioTeam/YAMLCord#16]
Import paths are too messy to handle, it should be fixed using import alias.
But in the other hand, we should need to fix the imports from the playground to avoid build errors from Cloudflare.
We should use the package from npm.

**Comment by hozhai** [comment]
Self assigned

**Comment by LonelyDeathVGX** [comment]
Using the `yamlcord` (formerly `fancyscript-yaml`) dependency refers to using the package in the Documentation Playground.

**Comment by LonelyDeathVGX** [comment]
This seems to be halfway complete. The package will be used in the Playground, as per Issue #58
