### ISSUE TITLE
Built-in function should have a prefix or suffix

### ISSUE THREAD

**Issue by Dymidless** [FancyStudioTeam/YAMLCord#56]
[Link on the project](https://github.com/orgs/FancyStudioTeam/projects/3?pane=issue&itemId=80647254)

**Comment by LonelyDeathVGX** [comment]
This should be discussed with the developers.
For now, it has been decided to use the `()` suffix.

**Comment by LonelyDeathVGX** [comment]
# Proposal Accepted
YAMLCord built-in function must have `()` suffix.

```yml
create_message(): "Hello, world!"
```

> [!NOTE]
> `()` suffix means that the structure is a YAMLCord built-in function.

**Comment by hozhai** [comment]
self assigned
